Add a pair for denominators not to be 0.  Refactor.

diff --git a/tools/shapeware_compare/shapeware_compare b/tools/shapeware_compare/shapeware_compare
--- a/tools/shapeware_compare/shapeware_compare
+++ b/tools/shapeware_compare/shapeware_compare
@@ -16,32 +16,35 @@ echo "created $spats_dir"
 cp spats.config "$spats_dir"
 cp "$json" "$spats_dir"
 
-for m in 1 2; do
-    touch "$spats_dir/test_S3_L001_R1_001.fastq"
-    touch "$spats_dir/test_S3_L001_R2_001.fastq"
-    for i in 1 2; do
-        fastq="$spats_dir/test_S3_L001_R${i}_001.fastq"
-        echo "@M05164:58:000000000-BW2LP:1:1101:1392${m}:502${m} ${i}:N:0:TAGCTT" >> "$fastq"
-        if [ "$m" -eq "1" ]; then 
-		    key="r${i}"
-            rd=`grep "\"${key}\"" "$json" | awk -F: '{print $2;}' | sed 's:[", ]::g'`
-            if [ "$i" -eq "1" ]; then
-                mask=`echo $rd | sed 's:^\(.\{4\}\).*$:\1:' | tr "[ACGT]" "[TGCA]"`
-            fi
-        else
-            # incl. mutations/indels only in treated
-		    key="r${i}_good"
-            rd=`grep "\"${key}\"" "$json" | awk -F: '{print $2;}' | sed 's:[", ]::g'`
-            if [ "$i" -eq "1" ]; then
-				rd=`echo $rd | sed 's:^\(.\{4\}\)\(.*\)$:\2:'`
-                rd="$mask""$rd"
-            fi
-        fi
-        echo "$rd" >> "$fastq"
-        echo "+" >> "$fastq"
-        grep "${key}_quality" "$json" | awk -F: '{print $2;}' | sed 's:[", ]::g' >> "$fastq" 
+
+write_fastq() {
+    fastq=$1
+    key=$2
+    rdi=$3
+    pair=$4
+    rd=`grep "\"${key}\"" "$json" | awk -F: '{print $2;}' | sed 's:[", ]::g'`
+    if [[ "$rdi" -eq "1"  &&  "$pair" -eq "2" ]]; then
+        mask=`echo $rd | sed 's:^\(.\{4\}\).*$:\1:' | tr "[ACGT]" "[TGCA]"`
+        rd=`echo $rd | sed 's:^\(.\{4\}\)\(.*\)$:\2:'`
+        rd="$mask""$rd"
+    fi
+    echo "@M05164:58:000000000-BW2LP:1:1101:1392${pair}:502${pair} ${rdi}:N:0:TAGCTT" >> "$fastq"
+    echo "$rd" >> "$fastq"
+    echo "+" >> "$fastq"
+    grep "${key}_quality" "$json" | awk -F: '{print $2;}' | sed 's:[", ]::g' >> "$fastq" 
+}
+
+touch "$spats_dir/test_S3_L001_R1_001.fastq"
+touch "$spats_dir/test_S3_L001_R2_001.fastq"
+for i in 1 2; do
+    fastq="$spats_dir/test_S3_L001_R${i}_001.fastq"
+    write_fastq "$fastq" "r${i}" $i 0
+    # always include one good of each handle for denominators not to be 0
+    for m in 1 2; do
+        write_fastq "$fastq" "r${i}_good" $i $m
     done
 done
+
 
 pushd "$spats_dir" > /dev/null
 
@@ -60,5 +63,6 @@ source activate shapeware
 
 eval "$shapeware" shapeware > shapeware.log 2>&1
 
-(open shapeware/plots/mut_identities/RRRY-test_YYYR-test_YYYR-test_bwa-mem_mutations.pdf && popd > /dev/null && rm -rf $spats_dir) || (echo "SHAPEware error occurred.  See $spats_dir/shapeware.log." && popd > /dev/null)
+#(open shapeware/plots/mut_identities/RRRY-test_YYYR-test_YYYR-test_bwa-mem_mutations.pdf && popd > /dev/null && rm -rf $spats_dir) || (echo "SHAPEware error occurred.  See $spats_dir/shapeware.log." && popd > /dev/null)
+(open shapeware/plots/mut_identities/RRRY-test_YYYR-test_YYYR-test_bwa-mem_mutations.pdf && popd > /dev/null) || (echo "SHAPEware error occurred.  See $spats_dir/shapeware.log." && popd > /dev/null)
 
