fix shapeware_compare quality-length issue

diff --git a/tools/shapeware_compare/shapeware_compare b/tools/shapeware_compare/shapeware_compare
--- a/tools/shapeware_compare/shapeware_compare
+++ b/tools/shapeware_compare/shapeware_compare
@@ -23,13 +23,15 @@ for m in 1 2; do
         fastq="$spats_dir/test_S3_L001_R${i}_001.fastq"
         echo "@M05164:58:000000000-BW2LP:1:1101:1392${m}:502${m} ${i}:N:0:TAGCTT" >> "$fastq"
         if [ "$m" -eq "1" ]; then 
-            rd=`grep "\"r${i}\"" "$json" | awk -F: '{print $2;}' | sed 's:[", ]::g'`
+		    key="r${i}"
+            rd=`grep "\"${key}\"" "$json" | awk -F: '{print $2;}' | sed 's:[", ]::g'`
             if [ "$i" -eq "1" ]; then
                 mask=`echo $rd | sed 's:^\(.\{4\}\).*$:\1:' | tr "[ACGT]" "[TGCA]"`
             fi
         else
             # incl. mutations/indels only in treated
-            rd=`grep "\"r${i}_good\"" "$json" | awk -F: '{print $2;}' | sed 's:[", ]::g'`
+		    key="r${i}_good"
+            rd=`grep "\"${key}\"" "$json" | awk -F: '{print $2;}' | sed 's:[", ]::g'`
             if [ "$i" -eq "1" ]; then
 				rd=`echo $rd | sed 's:^\(.\{4\}\)\(.*\)$:\2:'`
                 rd="$mask""$rd"
@@ -37,11 +39,11 @@ for m in 1 2; do
         fi
         echo "$rd" >> "$fastq"
         echo "+" >> "$fastq"
-        grep "r${i}_quality" "$json" | awk -F: '{print $2;}' | sed 's:[", ]::g' >> "$fastq" 
+        grep "${key}_quality" "$json" | awk -F: '{print $2;}' | sed 's:[", ]::g' >> "$fastq" 
     done
 done
 
-pushd $spats_dir > /dev/null
+pushd "$spats_dir" > /dev/null
 
 eval "${spats}" to_shapeware shapeware
 
@@ -58,7 +60,5 @@ source activate shapeware
 
 eval "$shapeware" shapeware > shapeware.log 2>&1
 
-open shapeware/plots/mut_identities/RRRY-test_YYYR-test_YYYR-test_bwa-mem_mutations.pdf
-
-popd
+(open shapeware/plots/mut_identities/RRRY-test_YYYR-test_YYYR-test_bwa-mem_mutations.pdf && popd > /dev/null && rm -rf $spats_dir) || (echo "SHAPEware error occurred.  See $spats_dir/shapeware.log." && popd > /dev/null)
 
